### ISSUE TITLE
Fork of this project

### ISSUE THREAD

**Issue by florian-lackner365** [julienadam/Setup_ELK#1]
Salut Julien !

J'espère que tu vas bien :)

Je suis en train de stocker les informations que tu m'as donné pour l'usage interne chez nous. Tu n'as pas ajouté une `LICENSE` à ce repo. Est-ce qu'on a le droit de le forker ? On fait ca souvent avec des resources qu'on utilise.

Bonne journée !
Flo

**Comment by julienadam** [comment]
Salut Flo,

Pas de souci, j'ai ajouté une licence MIT. N'hésite pas à forker ! Il faudra surement modifier certains fichiers, j'ai laissé des chemins en dur à quelques endroits...

A bientôt,

  Julien

**Comment by florian-lackner365** [comment]
merci bcp!
